---
title: "Gestion des doc distant"
author: "Expert.SLucien.data"
date: "2024-06-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Les étapes pour gestion cloner les doc
## Paramettrage de git en local
- cd "Mes doc/d1/DSTI_M2/MLOPS/github"

- git config --global user.name "Lucien Sy TRAORE"

- git config --global user.email luciensyt@gmail.com

- git init

## Première étape : cloner en local
- git add .

- git add "Doc_1.rmd" "Doc_2.py", utilisé en alternative de git add .

- git status, cette étape est optionnelle

- git commit -m "Le message du commit", envoie dans le dossier en local

## Deuxième étape : cloner en local
- git clone "chemin du dossier de depôt github sans les accolade", recupérer un travail depuis un depôt distant

- git push -u origin master, pour envoie dans dossier en ligne

- git log, pour voir la liste des commite en ligne faite

- git show, affiche le contenu du dossier cloner en ligne


## Etape de suppression d'un dossier distant
_ git rm --cached "nom_dossier distant", pour la supression dans le depôt distant

_ rm -rf "nom_dossier distant", pour la supression dans le depôt local

_ git commit -m "raison de la suppression"

_ git push origin master, mise à jour du depôt distant


